### ISSUE TITLE
Rewrite taglist

### ISSUE THREAD

**Issue by Westflow** [trpo2021/cw-is-042_is-041_iv-021_markdown_to_html#39]
# Брать вместе с #31 

Сейчас эта часть кода не используется, т.к не пригодилась. Предлагаю переписать ее для задачи #31.
Нужно где-то хранить символы для замены, удобно под это подойдет хэшмап.

**Comment by SFABUSER** [comment]
Я не стал переписывать, потому что заменять надо только скобки для тегов. Делать хэштаблицу ради этого зачем?

**Comment by Westflow** [comment]
> Я не стал переписывать, потому что заменять надо только скобки для тегов. Делать хэштаблицу ради этого зачем?

ok

**Comment by SFABUSER** [comment]
Закрываю тогда
