### ISSUE TITLE
Create Markdown to HTML hashmap

### ISSUE THREAD

**Issue by Westflow** [trpo2021/cw-is-042_is-041_iv-021_markdown_to_html#4]
# Описание.
Создать хэш-таблицу для хранения репрезентации тегов Markdown в HTML.

# Цель.
Хэш-таблица будет использоваться в парсинге для определения какому html тегу соответствует md тег.

# Подробнее.
Словарь должен поддерживать функцию TryGetValue, которая производит поиск по ключу (строке) и, при наличии поступившего ключа в словаре, возвращает value (строку).

# Пример:
Входные данные функции TryGetValue: `# `.
Выходные данные: `<h1>`.

**Comment by ArtemisGur** [comment]
Понял, босс
